pipeline:

  build-project:
    image: quay.io/ukhomeofficedigital/openjdk8:v1.1.0
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - ./gradlew build
    when:
     event: [push, pull_request, tag]

  build-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t pttg-fs-service .
    when:
      branch: master
      event: push

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - env
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-fs-service quay.io/ukhomeofficedigital/pttg-fs-service:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-fs-service:build-$${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: push

#
#  tag-docker-image-with-git-tag:
#    image: docker:1.11
#    environment:
#      - DOCKER_HOST=tcp://127.0.0.1:2375
#    commands:
#      - docker login -u="ukhomeofficedigital+pttg" -p=${DOCKER_PASSWORD} quay.io
#      - docker tag pttg-fs-service quay.io/ukhomeofficedigital/pttg-fs-service:${DRONE_TAG}
#      - docker push quay.io/ukhomeofficedigital/pttg-fs-service:${DRONE_TAG}
#    when:
#      event: tag
#
  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-pttg-fs-service.git
    when:
      event: [push, tag, deployment]

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v0.5.0
    environment:
      - KUBE_NAMESPACE=pttg-fs-dev
#      - ENVIRONMENT=dev
      - VERSION=build-$${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - kube_token
    commands:
      - cd kube-pttg-fs-service
      - ./deploy.sh
    when:
      branch: master
      event: [push, tag]
#
#  deploy-to-preprod-from-build-tag:
#    image: quay.io/ukhomeofficedigital/kd:v0.2.2
#    environment:
#      - DOCKER_HOST=tcp://127.0.0.1:2375
#      - KUBE_NAMESPACE=pt-i-preprod
#      - ENVIRONMENT=preprod
#      - VERSION=${DRONE_TAG}
#      - KUBE_SERVER=https://kube-dev.dsp.notprod.homeoffice.gov.uk
#    commands:
#      - cd kube-pttg-fs-service
#      - ./deploy.sh
#    when:
#      event: [tag]
#
#  deploy:
#    image: quay.io/ukhomeofficedigital/kd:v0.2.2
#    environment:
#      - DOCKER_HOST=tcp://127.0.0.1:2375
#      - KUBE_NAMESPACE=pt-i-${DRONE_DEPLOY_TO}
#      - ENVIRONMENT=${DRONE_DEPLOY_TO}
#      - VERSION=${IMAGE_VERSION}
#      - KUBE_SERVER=https://kube-dev.dsp.notprod.homeoffice.gov.uk
#    commands:
#      - cd kube-pttg-fs-service
#      - ./deploy.sh
#    when:
#      event: deployment
#      environment: [dev, test, preprod]
#
#  deploy-to-prod:
#    image: quay.io/ukhomeofficedigital/kd:v0.2.2
#    environment:
#      - DOCKER_HOST=tcp://127.0.0.1:2375
#      - KUBE_NAMESPACE=pt-i-prod
#      - ENVIRONMENT=prod
#      - VERSION=${IMAGE_VERSION}
#      - KUBE_SERVER=https://kube.dsp.digital.homeoffice.gov.uk
#    commands:
#      - cd kube-pttg-fs-service
#      - ./deploy.sh
#    when:
#      event: deployment
#      environment: prod
#
#services:
#  dind:
#    image: docker:1.11-dind
#    privileged: true
#    command:
#      - "-s"
#      - "overlay"