pipeline:

  experiment:
    image: quay.io/ukhomeofficedigital/kd:v0.2.2
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=pt-i-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER_DEV=https://kube-dev.dsp.notprod.homeoffice.gov.uk
    commands:
      - echo 'in experiment step (kd)'
    when:
      event: push

  experiment-success:
    image: quay.io/ukhomeofficedigital/kd:v0.2.2
    commands:
      - echo 'experiment step (kd) passed'
    when:
      status: success

  experiment-failure:
    image: quay.io/ukhomeofficedigital/kd:v0.2.2
    commands:
      - echo 'experiment step (kd) failed'
    when:
      status: failure

  build:
    privileged: true
    image: quay.io/ukhomeofficedigital/openjdk8:v1.0.0
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - ./gradlew build
    when:
      event: [push, pull_request, tag]

  create-docker-image:
    privileged: true
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t pttg-fs-service .
    when:
      branch: [master, refs/tags/*]
      event: [push, pull_request, tag]

  push-image-to-quay:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - echo "in push-image-to-quay with DOCKER_PASSWORD=" ${DOCKER_PASSWORD}
      - docker login -u="ukhomeofficedigital+pttg" -p=${DOCKER_PASSWORD} quay.io
      - docker tag pttg-fs-service quay.io/ukhomeofficedigital/pttg-fs-api:latest
      - docker tag pttg-fs-service quay.io/ukhomeofficedigital/pttg-fs-api:build-${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-fs-api:latest
      - docker push quay.io/ukhomeofficedigital/pttg-fs-api:build-${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: [push, pull_request]

  push-image-to-quay-with-git-tag:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=${DOCKER_PASSWORD} quay.io
      - docker tag pttg-fs-service quay.io/ukhomeofficedigital/pttg-fs-api:${DRONE_TAG}-${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-fs-api:${DRONE_TAG}-${DRONE_BUILD_NUMBER}
    when:
      event: tag

  get-kube-project:
    image: plugins/git
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - git clone https://github.com/UKHomeOffice/kube-pttg-fs-service.git
    when:
      branch: master
      event: [push, deployment, tag]

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=pt-i-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER_DEV=https://kube-dev.dsp.notprod.homeoffice.gov.uk
    commands:
      - cd kube-pttg-fs-service
      - ./deploy.sh
    when:
      branch: master
      event: push

  deploy_to_test:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=pt-i-test
      - ENVIRONMENT=test
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER_DEV=https://kube-dev.dsp.notprod.homeoffice.gov.uk
    commands:
      - cd kube-pttg-fs-service
      - ./deploy.sh
    when:
      event: deployment
      environment: test

  deploy_to_preprod:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=pt-i-preprod
      - ENVIRONMENT=preprod
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER_DEV=https://kube-dev.dsp.notprod.homeoffice.gov.uk
    commands:
      - cd kube-pttg-fs-service
      - ./deploy.sh
    when:
      event: deployment
      environment: preprod

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=pt-i-prod
      - ENVIRONMENT=prod
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER_PROD=https://kube.dsp.digital.homeoffice.gov.uk
    commands:
      - cd kube-pttg-fs-service
      - ./deploy-prod.sh
    when:
      event: deployment
      environment: prod

services:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"