pipeline:

  experiment:
    image: quay.io/ukhomeofficedigital/kd:v0.2.2
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=pt-i-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER_DEV=https://kube-dev.dsp.notprod.homeoffice.gov.uk
    commands:
      - echo 'in experiment step (kd)'
    when:
      event: push

  
services:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"